### ISSUE TITLE
ruby 2.0 32 bit win compilation fails due to compiler requirement in config.h

### ISSUE THREAD

**Issue by tdapper** [SketchUp/ruby-c-extension-examples#10]
For the 64 bit versions, you modified the config.h file from the Ruby includes by commenting out the requirement for a specific compiler version by commenting out this:
```c++
#if _MSC_VER != 1600
#error MSC version unmatch: _MSC_VER: 1600 is expected.
#endif
```
The 32 bit include still has this and compilation with Visual Studio 2015 therefore fails.

**Comment by thomthom** [comment]
Ruby 2.2 was compiled for VS2010. If you want to build with newer VS version you need to edit out that file. You might also have to manually define some macros to account for compiler differences. You can see example of what I did for TT_Lib: https://bitbucket.org/thomthom/tt-library-2/src/89d1078a79202daa482c71f3648aac0e6bf0bcb6/cext/tt_lib2/tt_lib2/src/ruby/framework.h?at=Version_2.10&fileviewer=file-view-default

**Comment by tdapper** [comment]
I think there is a misunderstanding. Please just try to grab this repository, load SketchUp Ruby C Extension Examples.sln in Visual Studio 2015 (because that is what the workspace is set up for I guess) and try to build SUEX_HelloWorld in the Release (2.0)|Win32 config.

It will fail because of missing modifications in ThirdParty\include\ruby\2.0\win32\i386-mswin32_100\ruby\config.h. The modifications that are needed to compile have been applied to C:\Users\timm\Documents\Laubwerk\ruby-c-extension-examples\ThirdParty\include\ruby\2.0\win32_x64\x64-mswin64_100\ruby\config.h, so the Release (2.0)|x64 configuration compiles fine. After applying similar modifications to the former config.h, Win32 also compiles. However, it would be great for the example project to already contain them.

**Comment by thomthom** [comment]
Ah, gotcha. Yea, we probably forgot to test the 32bit builds.

You mentioned you got it working, is that something you can send us a Pull Request for?

**Comment by tdapper** [comment]
Totally, will do.
