### ISSUE TITLE
The Sketchup&&LayOut 2017 SDK BUG

### ISSUE THREAD

**Issue by JackTing** [SketchUp/ruby-c-extension-examples#12]
Hi:
I download the 2017 SketchupAPI SDK and LayOutAPI SDK, I use RubyExampleCreateLayOut sample,but create .so file can't work on Sketchup2017. But I use MacOS, the same project work well.

I test the code:
this code not work,if I use LOInitialize;

``` c++
 VALUE create_layout_doc(VALUE self, VALUE skp_path) {
      LOInitialize();
      return Qtrue;
}
```
But this code not work:
``` c++
 VALUE create_layout_doc(VALUE self, VALUE skp_path) {
      return Qtrue;
}
```

**Comment by JackTing** [comment]
My IDE is vs 2015

**Comment by thomthom** [comment]
Can yoy elaborate on what doesn't work? What are you observing?

**Comment by JackTing** [comment]
Errorcode:
``` ruby
Error: C:/Program Files/SketchUp/SketchUp 2017/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Program Files/SketchUp/SketchUp 2017/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Users/ding/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Plugins/Aladdin/tools/constructions/drawing_manager.rb:15:in `export_layout_file'
......
```

**Comment by thomthom** [comment]
You mention `create_layout_doc` didn't work, but `create_layout_doc` did? Can you elaborate on that? Are you building the project yourself?

**Comment by JackTing** [comment]
Well:
1: I download the Sketchup2017 and LayOut sdk.
2: I build the RubyExampleCreateLayOut  project.
    the ruby lib is 2.2.4, build project no error.
3: I copy the CreateLayOutExample.so and createLayOut.rb to  Sketchup2017 plugins folder
4: Start Sketchup 2017
5: Click the CreateLayoutExample command
the error code is:
``` ruby
Error: C:/Program Files/SketchUp/SketchUp 2017/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Program Files/SketchUp/SketchUp 2017/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Users/ding/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Plugins/createLayOut.rb:29:in `run'
C:/Users/ding/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Plugins/createLayOut.rb:109:in `block in <module:CreateLayOutExample>'
SketchUp:1:in `call'

```

**Comment by thomthom** [comment]
It looks like there is a regression in SU2017 where `SketchUpViewerAPI.dll` is missing from the SketchUp installation directory.

As a work-around users can copy the file from `C:\Program Files\SketchUp\SketchUp 2017\LayOut` to `C:\Program Files\SketchUp\SketchUp 2017` and the sample should work again.

Can you see if the example works for you by copying over the DLL?

This issue has been filed internally and we'll get it updated in next release.

There is a discussion on the forum which appear to be related:
http://forums.sketchup.com/t/the-sketchupapi-layoutapi-2017-sdk-bug/36164/2?u=tt_su

**Comment by JackTing** [comment]
Great，the plugin can works.
Thanks for your help!

**Comment by DanRathbun** [comment]
@thomthom 
> This issue has been filed internally and we'll get it updated in next release.

I noticed in old versions (ie, SU2016) the dll was named "`sketchupviewer.dll`" and that by the release **`17.2`** cycle it had been corrected to be named "`SketchUpViewerAPI.dll`".

**So can this issue be closed ?**
