### ISSUE TITLE
Newbie problem - creating corresponding rbz?

### ISSUE THREAD

**Issue by amolnr** [SketchUp/ruby-c-extension-examples#13]
Hi,
I'm trying to get this HelloWorld project for SketchUp running with win7 with VS 2015 and SU2016 - I t I do it would try it without "SWING"
without success...
I'm missing the ruby code or extension; that would run .so file, and did not manage to make it based on the SketchUp extension su_create_layout_file...

the same problem the other way around:
**I've written a C program which runs good as an exe, and would like to create a Sketchup Extension from it... I've tried to start with the github HelloWorld project, but did not manage to create the appropriate rb file to get it work... I recieve an error message:

Error: 193: %1 ist keine zulässige Win32-Anwendung. - path of .so file
which means "is no valid" Win-32 application....

what did I do wrong?**

Could you give me any clue please...
Thanks in advance!

see also:
https://forums.sketchup.com/t/problem-on-c-ruby-extension/31386/3

**Comment by salgue** [comment]
Hello @amolnr, these examples requite SU2017 additionally, SU2017 SDK only supports x64.

@thomthom I think we should update README.md and add the requirements, additionally we should want to add tags (example: SU2016_VS2015) just in case a developer is trying to build these examples for older versions of SketchUp.

**Comment by amolnr** [comment]
OK, I'll try with that - but is the way similar in case of SU2016?

**Comment by salgue** [comment]
For SU2016 you will have to use SU2016 SDK.

On another note, I think I understand your issue better: the SDK package has sample project called "licensed_ruby_extension" that shows how to create C extensions using ruby, give that a try since it's a complete project with C and ruby code.

**Comment by amolnr** [comment]
Hello @salgue 
following your notes I switched to experiment with SU2017. (Because of ruby complications using VS2015).

So I tried to build and run the sample for SU2017:
SDK_Win_17-0-18899_0\samples\RubyExampleCreateLayOut

it builds nicely
I even manage to require the ruby extension  - it creates the Extension.
but upon calling the extension it drops an error message:
Error: #<LoadError: 126: Das angegebene Modul wurde nicht gefunden.   - C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOutExample.so>
C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:29:in `require_relative'
C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:29:in `run'
C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:108:in `block in <module:CreateLayOutExample>'
SketchUp:1:in `call'

module not found...

Where did I do wrong???

**Comment by thomthom** [comment]
The RubyExampleCreateLayOut is using the LayOut C API - is that what you are trying to do?

> I switched to experiment with SU2017. (Because of ruby complications using VS2015).

What complications was that?

**Comment by amolnr** [comment]
Complication: it just dont wanted to get compiled - I think it was that the ruby version I installed has been compiled with VS2013 and something doesn't match the VS2015 things...

LayOut C API - yes - I've written an "exe" which helps adjusting the dimension extension lines in a Layout file...

But the problem I have seems to be a "basic" one... So far I did not manage to "require" a .so module and call a function from SketchUP ruby...

**Comment by thomthom** [comment]
I'm a little confused to exactly which example you are trying to compile and what your setup is right now. You mention you got an exe application, but we're talking about a Ruby C Extension here, right?

Are you trying to use the LayOut API in a Ruby C Extension?

Or are you trying to make a Ruby C Extension for SketchUp - not using the C API at all?

**Comment by amolnr** [comment]
Sorry, I felt, I'm confusing....

Final goal: to build from the "exe" which uses LayOut API an extension for SketchUP - similar to "su_create_layoutfile" in a way, that it is launched from SketchUP but targets LayOUT actions...

I thougt if I achive step 1 with your help, I'll manage to reach the final goal.

Step 1: to build "any" Ruby C Extension...
main constraints: Win7 environment with VS2015
SU2016 or SU2017 version

my last experiment was with the 
SDK_Win_17-0-18899_0\samples\RubyExampleCreateLayOut
followed by the post above:

> 
> Hello @salgue
> following your notes I switched to experiment with SU2017. (Because of ruby complications using VS2015).
> 
> So I tried to build and run the sample for SU2017:
> SDK_Win_17-0-18899_0\samples\RubyExampleCreateLayOut
> 
> it builds nicely
> I even manage to require the ruby extension - it creates the Extension.
> but upon calling the extension it drops an error message:
> Error: #<LoadError: 126: Das angegebene Modul wurde nicht gefunden. - C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOutExample.so>
> C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:29:in require_relative' C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:29:inrun'
> C:/***/RubyExampleCreateLayOut/Release_x64/CreateLayOut.rb:108:in block in <module:CreateLayOutExample>' SketchUp:1:incall'
> 
> module not found...
> 
> Where did I do wrong???

If you are more familiar with the "HelloWorld" or any other C extension, just tell me, which one I should follow..

Correct me if my strategy is wrong...

Thanks!



Thanks in advance...

**Comment by amolnr** [comment]
Tonight I've started again trying to get the "hello_world" running... - with SUCCESS! - DOUBLE SUCCESS.
(OK, for "pro" members it will seem all stupid, but I'm happy about it...)

So the clue was to
- run always the x64 versions since the machine is x64
-and that SU2016 accepts ruby 2.0 and SU2017 accepts ruby 2.2
(otherwise it drops the error message: "LoadError: 126: Das angegebene Modul wurde nicht gefunden")

so the steps I've followed:
1) download and unzip "https://github.com/SketchUp/ruby-c-extension-examples"
2) open solution in VS2015 build 2.0 and 2.2 with x64
3) run the project from SketchUP Ruby Console:

on Win7 x64 + SU2016 + VS2015:
require 'C:/***/ruby-c-extension-examples-master/Debug (2.0)/x64/SUEX_HelloWorld.so'
SUEX_HelloWorld::hello_world

on Win7 x64 + SU2017 + VS2015:
require 'C:\***\ruby-c-extension-examples-master\Release (2.2)\x64/SUEX_HelloWorld.so'
SUEX_HelloWorld::hello_world

@salgue and @thomthom - many thanks for being patient... and pls correct me if I'm not correct at some points...

**Comment by salgue** [comment]
Yeey! I'm happy you got it working 👍
