### ISSUE TITLE
use SDK_Mac_17-0-18898 and ruby-c-extension-examples BUG

### ISSUE THREAD

**Issue by gaolei** [SketchUp/ruby-c-extension-examples#14]
incompatible library version - SUEX_HelloWorld_2017/SUEX_HelloWorld.bundle

Xcode Version 8.2.1 (8C1002)
ruby-c-extension-examples master
SDK_Mac_17-0-18898

add SketchUpAPI.framework to project , build 。 sketch 2017 pro ruby console，require 。

got “incompatible library version ” error

**Comment by thomthom** [comment]
@salgue any chance you can look at this one?

**Comment by salgue** [comment]
Hello @gaolei , I was able to build the bundles using Xcode 8.2.1, can you please provide more details? steps to reproduce and screenshots will help a lot, also feel free to attached a zip file with a sample project showing your scenario.

Thanks,
Sal

**Comment by thomthom** [comment]
Closing this as we've been unable to reproduce and not heard back.
