### ISSUE TITLE
What did you use to build Ruby 2.2.4 on Windows?

### ISSUE THREAD

**Issue by MarkcusD** [SketchUp/ruby-c-extension-examples#15]
It seems that version won't build with VS 2015.

**Comment by thomthom** [comment]
Ruby have never been too Visual Studio friendly unfortunately. We actually use the MingW version - which isn't ideal as we are unable to step through Ruby's C code when we need to debug SketchUp.
We get our build packages from https://rubyinstaller.org/

**Comment by MarkcusD** [comment]
Ok thanks.
