### ISSUE TITLE
SUEX_UsingSWIG - Include directory points to Ruby 2.0 instead of 2.2 in Release (2.2) x64 / Win32

### ISSUE THREAD

**Issue by akav** [SketchUp/ruby-c-extension-examples#17]
I noticed that the include directory for Release/Debug (2.2) win32 and x64 point to 2.0 Ruby folder . Should it be pointing to 2.2 folder instead?

Also I am receiving the following error in VS2015 with when compiling using /MT in Release (2.2) x64:
c:\ruby-c-extension-examples\thirdparty\include\ruby\2.2\win32_x64\ruby/missing.h(76): error C2375: 'acosh': redefinition; different linkage

C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\math.h(477): note: see declaration of 'acosh'

Within this configuration for Release 2.2 in Linker > Input > Dependencies it links x64-msvcrt-ruby200.lib instead of x64-msvcrt-ruby220.lib.  Is it possible that the 220 lib has been compiled with /MD instead of /MT?

Thanks,
Anthony

**Comment by DanRathbun** [comment]
I do not see the error in the 2.2 configuration pointing to Ruby 2.0. Can you be specific as to file name and folder ?
(Perhaps this was fixed when the files for Ruby 2.5 were added?)

> @akav  Is it possible that the 220 lib has been compiled with /MD instead of /MT?

The README clearly says under section [**Windows and Runtime DLLs**
](https://github.com/SketchUp/ruby-c-extension-examples#windows-and-runtime-dlls) ...
> _SketchUp itself builds Ruby with dynamic CRT - using the **`/MD`** flag._

There is a paragraph near the bottom on compiling with a `/MT` switch.

**Comment by akav** [comment]
Thank you for the update and the documentation link. I think that at the time I was looking at the samples, the issue was in the VS solution. But I will clone and re-do the process of building and running the samples to confirm. As its been two years its quite possible as you mentioned that this was indeed corrected so I am closing this.
