### ISSUE TITLE
Can GetRubyInterface() be aliased?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-c-extension-examples#19]
REF: `"src/RubyUtils/RubyUtils.h"`

Can `GetRubyInterface()` be aliased? It is quite a long function name (16 chars) and will serve to make code noisier.

How about something shorter that indicates a conversion to `VALUE` ? 
Ideas in order of preference:
* `VAL()`
* `val()`
* `value()`
* `C2VAL()`

**Comment by thomthom** [comment]
`GetRubyInterface` is the function name SketchUp have been using internally. The conversion functions where copied from the SketchUp source. I don't think we'll be changing this naming now - it's a very subjective issue. This is just an example after all and people can adapt it as they please.

Personally I think I used `GetVALUE` in my own extensions. But I also use a C++ wrapper which makes interacting with Ruby more familiar.

**Comment by DanRathbun** [comment]
I think I meant would it be easier for a coder to alias it, and just keep the rest of the template as it is so when it is updated, they just sync their clone.

At the top of the first coder's project file would they use a `#define` if they wish to alias it ?

> ... it's a very subjective issue.

Who (as a programmer) desires to name a conversion function (that'll be repetitively typed like about everywhere in just about every function call,) ... with a 16 character name ?

**Do so is objectively ridiculous !**

**Comment by thomthom** [comment]
`GetRubyInterface` is used all over SketchUp's source... Yea, it's somewhat verbose and I would probably not have picked such a name myself. But this issue is realistically not going to be of a high enough priority for us to address.

**Comment by DanRathbun** [comment]
I'm asking a question if they is any problem with a coder defining an alias in THEIR code ? (But your code remains the same.)

**Comment by thomthom** [comment]
Ah, I didn't pick up on that. Sure, thevname doesn't havebany technical restrictions to it.
I'm not sure how you where thinking of aliasing it though. Renaming them? #defines?  (I'd avoid that)

**Comment by DanRathbun** [comment]
Yes I'm not much of a C connoisseur, so I think that I've seen #define used to alias functions, but I don't know if that is the best way or has drawbacks.

**Comment by thomthom** [comment]
`#define` is a pre-processor directive and they make it difficult to debug because they alter the source code being compiled from what is in the source file. They are also global and can easily clash.

I don't really know if any way to alias functions in C/C++ as you can do in Ruby. You can wrap functions, but for these functions it's probably easiest to just copy+paste and rename them.
