### ISSUE TITLE
Linking errors when building bundles on Xcode

### ISSUE THREAD

**Issue by Whaat** [SketchUp/ruby-c-extension-examples#23]
I checked out dev/arm64 and tried to build the project and got this error

ld: warning: ignoring file /Users/dalemartens/mind.sight.studios Dropbox/Dale Martens/Plugins/ruby-c-extension-examples/ThirdParty/lib/mac/2.7-universal/Ruby.framework/Ruby, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 )

Running MacOS 12.1 and Xcode 13.2.1 on an M1 Mac mini

**Comment by thomthom** [comment]
I just cloned the branch  fresh on my M1 Mac Mini and hit Build. But I wasn't seeing any linker errors.

Xcode 13.1
macOS 11.6

Are you still seeing this?

**Comment by Whaat** [comment]
Sorry, haven't had a chance to test this again.  I'd be curious if you would see the errors if you had the same OS and Xcode version that I have.  Not an urgent issue for me - I was able to build all of my extensions for arm64 although I can't say it was easy, especially the ones that use third party dylibs

**Comment by tommash** [comment]
Does all third party dylibs have to be built for arm too?

**Comment by Whaat** [comment]
Yes, they do in my experience

**Comment by thomthom** [comment]
I'm assuming this issue has been solved?
