### ISSUE TITLE
Does this project still work in SUP2021？

### ISSUE THREAD

**Issue by panda8246** [SketchUp/ruby-c-extension-examples#24]
I use VS2019 build the 'HelloWorld' project and require .so file in ruby console by one line code：
```
require 'F:/Data/ruby-c-extension-examples-main/Release (2.2)/x64/SUEX_HelloWorld.so'
```
But I get an error:
```
Error: #<LoadError: 126: \x{D5D2}\x{B2BB}\x{B5BD}\x{D6B8}\x{B6A8}\x{B5C4}\x{C4A3}\x{BFE9}\x{A1A3}   - F:/Data/ruby-c-extension-examples-main/Release (2.2)/x64/SUEX_HelloWorld.so>
E:/SketchUp/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
E:/SketchUp/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:92:in `require'
<main>:in `<main>'
SketchUp:in `eval'
```
My friend use the same way to build it and work well.His SUP version is 2018,so I wonder if this project is still valid in SUP2021.

**Comment by thomthom** [comment]
Yea, should work.

That error message is curious though `\x{D5D2}\x{B2BB}\x{B5BD}\x{D6B8}\x{B6A8}\x{B5C4}\x{C4A3}\x{BFE9}\x{A1A3}`. Never seen that.

**Comment by thomthom** [comment]
Wait, `require 'F:/Data/ruby-c-extension-examples-main/Release (2.2)/x64/SUEX_HelloWorld.so'` loads the binary for Ruby 2.2. But SU2021 uses Ruby 2.7. There are multiple variants being built in that project, depending on target SU version. For SU2021 you need to load the one for Ruby 2.7.

**Comment by panda8246** [comment]
Thanks! This helped me a lot. I rebuild it with Release(2.7), now it works well.
