### ISSUE TITLE
Extension which uses Z depth/Z channel

### ISSUE THREAD

**Issue by BenjaminIrwin** [SketchUp/ruby-c-extension-examples#27]
Hi,

The contact part of the developer site was giving me a 404 and I can't find anything on the docs nor in the examples in this repo to provide an answer to this.

I want to create an extension which uses the (inverted) z depth/z channel of the user's sketchup model. This tweet was my inspiration:

https://twitter.com/hardmaru/status/1601513412575793155

I'm wondering how I can extract this data in SketchUp? If you could give me any pointers I would be very grateful.

Thank you in advance!

**Comment by thomthom** [comment]
Hi, which contact part of the developer site is giving 404? Can you post the link that give 404 and where that's linked from?

For API usage questions the forums is where we direct people: https://forums.sketchup.com/c/developers/12
For bug reports/feature requests we have an issue tracker: https://github.com/SketchUp/api-issue-tracker
