### ISSUE TITLE
Update SLAPI How-To

### ISSUE THREAD

**Issue by thomthom** [SketchUp/ruby-c-extension-examples#5]
https://github.com/SketchUp/ruby-c-extension-examples/wiki/Adding-SLAPI-to-Visual-Studio

The whole example needs updating, to reflect the name change of the C API dlls.

**Comment by rstuannm** [comment]
are you have source code for this example? please sent me this link.
the source in github difference with it.
thanks.

**Comment by thomthom** [comment]
There isn't any source code change to use SLAPI 64bit. You just got to make sure you pick the 64bit libs for the x64 config.
