### ISSUE TITLE
Ruby 2.2 mac has a huge number of files not existing in 2.0 or 1.8

### ISSUE THREAD

**Issue by tdapper** [SketchUp/ruby-c-extension-examples#8]
I am not completely sure if this actually is a problem, but the 2.2 mac lib has a folder structure that has a few hundred files in it while the older versions (2.0, 1.8) don't have that. Just checking if these are really needed.

**Comment by thomthom** [comment]
Hm... looks like you are right. The 2.2 version seem to include the StdLib files - which isn't needed to build C Extension. Where as previously we'd stripped them away.

I think it makes sense to strip it. @salgue - thoughts?

**Comment by salgue** [comment]
@thomthom I agree, lets test the examples after stripping these out.

**Comment by tdapper** [comment]
Thanks for looking into this @thomthom and @salgue!
